# Generated by Django 5.0.3 on 2024-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default='Tennessee', max_length=100),
            preserve_default=False,
        ),
    ]
