# Generated by Django 5.0.3 on 2024-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_article_location_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(default='Tennessee Pollution', max_length=100),
        ),
    ]
