# Generated by Django 5.0.3 on 2024-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_article_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='terms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
