# Generated by Django 5.0.3 on 2024-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_article_cities_article_county_article_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='articles',
            field=models.ManyToManyField(related_name='search_queries', to='homepage.article'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
