# Generated by Django 5.0.3 on 2024-04-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_searchquery_articles_searchquery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='results',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='searched_on',
        ),
    ]
