# Generated by Django 5.0.3 on 2024-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_searchquery_articles_searchquery_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='date',
        ),
    ]
